dataSource:
  mysql:
    username: root
    password: 124563
    host: 127.0.0.1
    port: 3306
    timeLoc: Asia/Shanghai
    database: fileserver
    maxIdle: 10
    maxOpenConn: 100
    maxLifeTime: 720
  redis:
    addr: localhost:6379
    password: ""
    database: 0

mq:
  rabbit:
    url: amqp://guest:guest@192.168.47.132:5672/
    exchangeName: uploadserver.trans
    cephQueueName: uploadserver.trans.ceph
    cephErrQueueName: uploadserver.trans.ceph.err
    cephRoutingKey: ceph
    cephErrRoutingKey: ceph.err

store:
  ceph:
    accessKey: H891OGRD30U25YW3FX77
    secretKey: bXX9xl5JfVyQd8SsD36bUPz30afV0wQrgKMEl6qN
    regionName : default
    endpoint: http://192.168.47.132:9080
    S3LocationConstraint: false
    S3LowercaseBucket: false
    fileStoreBucketName: files
    putBinDataContentType: octet-stream
    filePathPrefix: /ceph/

business:
  uploadServiceEndpoint: http://localhost:9000
  fileStorePath: E:/go/go-disk/filestore/

micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
  client:
    auth:
      serviceName: go.micro.service.auth
