dataSource:
  redis:
    addr: localhost:6379
    password: ""
    database: 1
    tokenExpireTime: 72 #hour
  mysql:
    username: root
    password: 124563
    host: 127.0.0.1
    port: 3306
    timeLoc: Asia/Shanghai
    database: fileserver
    maxIdle: 10
    maxOpenConn: 100
    maxLifeTime: 720
micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
business:
  userPasswordSalt: 1104459