dataSource:
  mysql:
    username: root
    password: 124563
    host: 127.0.0.1
    port: 3306
    timeLoc: Asia/Shanghai
    database: fileserver

store:
  ceph:
    accessKey: HC6D02PA698NDEGHDNGU
    secretKey: kHOAsvDkSFg5ay6JcNEmINHg1eVWUmkSeuZMZYLs
    regionName : default
    endpoint: http://192.168.47.132:9080
    S3LocationConstraint: false
    S3LowercaseBucket: false
    fileStoreBucketName: files
    putBinDataContentType: octet-stream
    filePathPrefix: /ceph/

micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
